import pytest

"""def test_exception():
    try:
        funcion_with_exception(0)
    except Exception as e:
        assert e"""

"""def test_exception():
    with pytest.raises(Exception):
        funcion_with_exception(0)
"""

"""
def test_exception():
    with pytest.raises(Exception) as e:
        funcion_with_exception(0)
    assert str(e.value) == "ожидаемое сообщение из исключения"
"""